[package]
name = "halo2-snark-aggregator-circuit"
version = "0.1.0"
edition = "2021"
authors = ["zhangjunyu <junyu92@gmail.com>"]

[dependencies]
clap = { version = "3.1.11", features = ["derive"] }
halo2_ecc = { git = "https://github.com/jonathanpwang/halo2-ecc", branch = "scroll-aggregator", default-features = false }
halo2-snark-aggregator-api = { path = "../halo2-snark-aggregator-api" }
halo2_proofs = { version = "0.1.0-beta.1" }
ff = "0.11"
log = "0.4.17"
pairing_bn256 = { git = "https://github.com/appliedzkp/pairing", tag = "v0.1.1" }
rand = "0.8.5"
rand_core = "0.6.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 ="0.10.2"
sha3 = "0.10.1"
rayon = "1.5.2"
num-bigint = { version = "0.4", features = ["rand"] }

[dev-dependencies]
ark-std = { version = "0.3", features = ["print-trace"] }
eth-types = { git = "https://github.com/ZhenXunGe/zkevm-circuits.git", branch = "zhangjunyu/halo2_proofs" }
zkevm-circuits = { git = "https://github.com/ZhenXunGe/zkevm-circuits.git", branch = "zhangjunyu/halo2_proofs" }

[features]
default = ["halo2"]
blake2b = []
halo2 = []
plonk = []
benches = []
